In [1]:
import pandas as pd

In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
titanic_train = pd.read_csv("train.csv")   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [8]:
titanic_train.tail(15)

PassengerId  Survived  Pclass  \
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                              Name     Sex   Age  SibSp  \
876                  Gustafsson, Mr. Alfred Ossian    male  20.0      0   
877                           Petroff, Mr. Nedelio    male  19.0      0   
878                             Laleff, Mr. Kristo    male   NaN      0   
879  Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880   Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
881                             Markun, Mr. Johann    male  33.0      0   
882                   Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
883                  Banfield, Mr. Frederick James    male  28.0      0   
884                         Sutehall, Mr. Henry Jr    male  25.0      0   
885           Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                          Montvila, Rev. Juozas    male  27.0      0   
887                   Graham, Miss. Margaret Edith  female  19.0      0   
888       Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                          Behr, Mr. Karl Howell    male  26.0      0   
890                            Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
876      0              7534   9.8458   NaN        S  
877      0            349212   7.8958   NaN        S  
878      0            349217   7.8958   NaN        S  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
881      0            349257   7.8958   NaN        S  
882      0              7552  10.5167   NaN        S  
883      0  C.A./SOTON 34068  10.5000   NaN        S  
884      0   SOTON/OQ 392076   7.0500   NaN        S  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q

In [9]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
titanic_train['Survived'].unique()

array([0, 1], dtype=int64)

In [18]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [22]:
titanic_train['Name'].describe()

count                         891
unique                        891
top       Braund, Mr. Owen Harris
freq                            1
Name: Name, dtype: object

In [6]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[a].describe()


Name   Sex    Ticket Cabin Embarked
count                 891   891       891   204      889
unique                891     2       681   147        3
top     Kantor, Mr. Sinai  male  CA. 2343    G6        S
freq                    1   577         7     4      644

In [7]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [8]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [9]:
titanic_train.dtypes[titanic_train.dtypes == "object"]


titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [10]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [11]:
list_col = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[list_col].describe()

Name   Sex    Ticket Cabin Embarked
count                 891   891       891   204      889
unique                891     2       681   147        3
top     Kantor, Mr. Sinai  male  CA. 2343    G6        S
freq                    1   577         7     4      644

In [12]:
titanic_train[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [13]:
sorted(titanic_train["Name"])[5:10:2]# Check the first 15 sorted names

['Adahl, Mr. Mauritz Nils Martin',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Albimona, Mr. Nassef Cassem']

In [14]:
titanic_train["Name"].describe()

count                   891
unique                  891
top       Kantor, Mr. Sinai
freq                      1
Name: Name, dtype: object

In [15]:
titanic_train[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [16]:
titanic_train["Ticket"].describe()
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [24]:
titanic_train["keshav"]=list(range(891))
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  keshav  
0      0         A/5 21171   7.2500   NaN        S       0  
1      0          PC 17599  71.2833   C85        C       1  
2      0  STON/O2. 3101282   7.9250   NaN        S       2  
3      0            113803  53.1000  C123        S       3  
4      0            373450   8.0500   NaN        S       4

In [18]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [19]:
titanic_train.dtypes# Check number of unique cabins

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
keshav          object
dtype: object

In [20]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [21]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'keshav'],
      dtype='object')

In [22]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [25]:
titanic_train["Pclass"].unique()

array([3, 1, 2], dtype=int64)

In [23]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [24]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [25]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [26]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin


['n', 'C', 'n', 'C', 'n', ..., 'n', 'B', 'n', 'C', 'n']
Length: 891
Categories (9, object): ['A', 'B', 'C', 'D', ..., 'F', 'G', 'T', 'n']

In [27]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  keshav  
0      0         A/5 21171   7.2500     n        S  keshav  
1      0          PC 17599  71.2833     C        C  keshav  
2      0  STON/O2. 3101282   7.9250     n        S  keshav  
3      0            113803  53.1000     C        S  keshav  
4      0            373450   8.0500     n        S  keshav

In [28]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [29]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [30]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([258, 679, 737], dtype=int64),)

In [31]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  keshav  
258  female  35.0      0      0  PC 17755  512.3292     n        C  keshav  
679    male  36.0      0      1  PC 17755  512.3292     B        C  keshav  
737    male  35.0      0      0  PC 17755  512.3292     B        C  keshav

In [32]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([258, 679, 737], dtype=int64),)

In [33]:
len(missing[0])

177

In [34]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([159, 180, 201, 324, 792, 846, 863], dtype=int64),)

In [35]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                               Name     Sex  \
159          160         0       3         Sage, Master. Thomas Henry    male   
180          181         0       3       Sage, Miss. Constance Gladys  female   
201          202         0       3                Sage, Mr. Frederick    male   
324          325         0       3           Sage, Mr. George John Jr    male   
792          793         0       3            Sage, Miss. Stella Anna  female   
846          847         0       3           Sage, Mr. Douglas Bullen    male   
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked  keshav  Family  
159  NaN      8      2  CA. 2343  69.55     n        S  keshav      10  
180  NaN      8      2  CA. 2343  69.55     n        S  keshav      10  
201  NaN      8      2  CA. 2343  69.55     n        S  keshav      10  
324  NaN      8      2  CA. 2343  69.55     n        S  keshav      10  
792  NaN      8      2  CA. 2343  69.55     n        S  keshav      10  
846  NaN      8      2  CA. 2343  69.55     n        S  keshav      10  
863  NaN      8      2  CA. 2343  69.55     n        S  keshav      10

In [36]:

d = {'a':"kjhk",'b':20,'c':30}
d.items
pd.DataFrame(d,index = ['a','b','c'])

a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [37]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  0.799764 -0.224784  1.879638 -1.355091
B  2.656388  0.577512 -0.248359  0.148391
C  0.388922  1.115818 -0.372564  0.059718
D -0.642277  0.209520 -0.535292 -0.589844
E -0.250791  0.023124  0.660829  0.570607

In [38]:
df.iloc[2]

W    0.388922
X    1.115818
Y   -0.372564
Z    0.059718
Name: C, dtype: float64

In [39]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [40]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df["X"])


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A   -0.224784
B    0.577512
C    1.115818
D    0.209520
E    0.023124
Name: X, dtype: float64


In [41]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)



A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A  0.799764 -0.224784  1.879638 -1.355091 -1.579875             -1.579875
B  2.656388  0.577512 -0.248359  0.148391  0.725902              0.725902
C  0.388922  1.115818 -0.372564  0.059718  1.175536              1.175536
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324             -0.380324
E -0.250791  0.023124  0.660829  0.570607  0.593730              0.593730


In [42]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.799764 -0.224784  1.879638 -1.355091 -1.579875             -1.579875
B  2.656388  0.577512 -0.248359  0.148391  0.725902              0.725902
C  0.388922  1.115818 -0.372564  0.059718  1.175536              1.175536
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324             -0.380324
E -0.250791  0.023124  0.660829  0.570607  0.593730              0.593730

In [43]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1




A column is dropped by using df.drop() method
 -------------------------------------------------------


In [44]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.799764 -0.224784  1.879638 -1.355091 -1.579875             -1.579875
B  2.656388  0.577512 -0.248359  0.148391  0.725902              0.725902
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324             -0.380324
E -0.250791  0.023124  0.660829  0.570607  0.593730              0.593730

In [45]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)



A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
B  2.656388  0.577512 -0.248359  0.148391  0.725902              0.725902
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324             -0.380324
E -0.250791  0.023124  0.660829  0.570607  0.593730              0.593730


In [46]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z       New
A  0.799764 -0.224784  1.879638 -1.355091 -1.579875
B  2.656388  0.577512 -0.248359  0.148391  0.725902
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324
E -0.250791  0.023124  0.660829  0.570607  0.593730


In [47]:
### Selecting/indexing Rows
#* Label-based 'loc' method
#* Index (numeric) 'iloc' method
df

W         X         Y         Z       New
A  0.799764 -0.224784  1.879638 -1.355091 -1.579875
B  2.656388  0.577512 -0.248359  0.148391  0.725902
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324
E -0.250791  0.023124  0.660829  0.570607  0.593730

In [48]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[3])



Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W     -0.250791
X      0.023124
Y      0.660829
Z      0.570607
New    0.593730
Name: E, dtype: float64


In [49]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])



Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W     -0.642277
X      0.209520
Y     -0.535292
Z     -0.589844
New   -0.380324
Name: D, dtype: float64


In [50]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Y         Z       New
B  2.656388  0.577512 -0.248359  0.148391  0.725902
D -0.642277  0.209520 -0.535292 -0.589844 -0.380324


In [51]:
#### Subsetting DataFrame

In [52]:

matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)



In [53]:
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)



The DatFrame
---------------------------------------------
          W         X         Y         Z
A -0.346412  1.437746 -0.626336  0.981403
B -0.851513  0.380408 -0.288247 -1.115134
C -2.388817 -1.394557  0.931874 -2.040182
D -0.427909 -0.319464  0.127603 -1.158553
E -0.141910 -0.126735 -1.768287 -0.148854


In [54]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])



Element at row 'B' and column 'Y' is

          Y         W
B -0.288247 -0.851513
C  0.931874 -2.388817


In [55]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
df.iloc[[1,2,3],[0,1]]


Subset comprising of rows B and D, and columns W and Y, is



W         X
B -0.851513  0.380408
C -2.388817 -1.394557
D -0.427909 -0.319464

In [56]:
print(df.loc[['B','C'],])

          W         X         Y         Z
B -0.851513  0.380408 -0.288247 -1.115134
C -2.388817 -1.394557  0.931874 -2.040182


In [57]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)



The DataFrame
---------------------------------------------
          W         X         Y         Z
A -0.346412  1.437746 -0.626336  0.981403
B -0.851513  0.380408 -0.288247 -1.115134
C -2.388817 -1.394557  0.931874 -2.040182
D -0.427909 -0.319464  0.127603 -1.158553
E -0.141910 -0.126735 -1.768287 -0.148854


In [58]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0)



Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A  False   True  False   True
B  False   True  False  False
C  False  False   True  False
D  False  False   True  False
E  False  False  False  False


In [59]:
print("\n")
print(df.loc[['A','B','C']]>0)




       W      X      Y      Z
A  False   True  False   True
B  False   True  False  False
C  False  False   True  False


In [60]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])


DataFrame indexed by boolean dataframe
---------------------------------------------
    W         X         Y         Z
A NaN  1.437746       NaN  0.981403
B NaN  0.380408       NaN       NaN
C NaN       NaN  0.931874       NaN
D NaN       NaN  0.127603       NaN
E NaN       NaN       NaN       NaN


In [61]:

import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [62]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)



A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [63]:
df[df['Height']>65]

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [64]:
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
print(df[df['Height']>65])



Rows with Height > 65 inch
-----------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160


In [65]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [66]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145


In [67]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])



Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160


In [68]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])


DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160


In [69]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [70]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)



The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [71]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())



After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [72]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()


After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [73]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)



Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse


In [74]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))


Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152
